# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-29 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('quote', models.CharField(max_length=100)),
                ('emailId', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path)),
                ('linkedIn', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
